export const CATEGORY_LANDING_PAGES = [
    {
        slug: 'food',
        label: 'Food in Harbour View',
        heading: 'Find food in Harbour View faster.',
        description: 'Browse Harbour View food spots, cook shops, bakeries, patties, jerk, takeaway options, and local restaurant listings in Kingston 17.',
        displayCategory: 'Food & Restaurants',
        searchTerm: 'food',
        heroBadge: '🍽️ Food & Restaurants',
        intro: 'When people search for food in Harbour View, they usually want something practical and nearby: lunch, patties, jerk, bakery items, seafood, or a quick takeaway option.',
        bullets: ['Lunch and quick meal options', 'Cook shops, bakeries, patties, and jerk', 'Listings structured for local search intent'],
    },
    {
        slug: 'pharmacy',
        label: 'Pharmacies in Harbour View',
        heading: 'Find pharmacy and health listings in Harbour View.',
        description: 'Browse pharmacy and health-related listings in Harbour View, Kingston 17, including practical local search paths for urgent everyday needs.',
        displayCategory: 'Health & Medical',
        searchTerm: 'pharmacy',
        heroBadge: '⚕️ Pharmacy & Health',
        intro: 'Pharmacy searches are high-intent and time-sensitive. This page narrows the wider health category down to the kind of listing people usually need quickly.',
        bullets: ['Pharmacy-oriented search intent', 'Health listings with clearer local relevance', 'Useful for urgent everyday needs'],
    },
    {
        slug: 'taxi',
        label: 'Taxi in Harbour View',
        heading: 'Find taxi and transport listings in Harbour View.',
        description: 'Search Harbour View taxi and transport listings in Kingston 17, with a simpler path for people trying to move quickly around the area.',
        displayCategory: 'Auto & Transport',
        searchTerm: 'taxi',
        heroBadge: '🚕 Taxi & Transport',
        intro: 'Taxi searches are rarely broad. Most people want a reachable transport option that makes sense for Harbour View, Kingston 17, or nearby East Kingston routes.',
        bullets: ['Transport-focused local search intent', 'Quick access to relevant listings', 'Better path for urgent mobility needs'],
    },
    {
        slug: 'mechanic',
        label: 'Mechanics in Harbour View',
        heading: 'Find mechanic and auto repair help in Harbour View.',
        description: 'Browse Harbour View mechanic and auto repair listings in Kingston 17, with a practical path for urgent car and transport-related searches.',
        displayCategory: 'Auto & Transport',
        searchTerm: 'mechanic',
        heroBadge: '🔧 Mechanic & Auto Repair',
        intro: 'Mechanic searches usually happen under pressure. This page narrows auto and transport listings toward repair-related intent so users can compare options faster.',
        bullets: ['Mechanic and repair-oriented search intent', 'Auto and transport listings filtered toward relevance', 'Useful for urgent breakdown and service searches'],
    },
    {
        slug: 'beauty',
        label: 'Beauty in Harbour View',
        heading: 'Find beauty and wellness listings in Harbour View.',
        description: 'Browse salons, braiders, barbers, nail services, and wellness-related listings in Harbour View, Kingston 17.',
        displayCategory: 'Beauty & Wellness',
        searchTerm: 'beauty',
        heroBadge: '💆 Beauty & Wellness',
        intro: 'Beauty searches tend to be specific: hair, braids, barbering, nails, lashes, or wellness services. This page groups those local-intent searches into one clearer path.',
        bullets: ['Hair, braids, barbering, nails, and wellness intent', 'A cleaner local landing page for beauty-related searches', 'Stronger internal linking target for blog and directory pages'],
    },
];

export function getCategoryLandingPage(slug) {
    return CATEGORY_LANDING_PAGES.find(page => page.slug === slug) || null;
}
